---
logging:
  level:
    ROOT: WARN
    com.giraone: INFO

server:
  port: 9083
  error.whitelabel.enabled: false

spring:
  application:
    name: queue-worker

management:
  endpoints:
    web:
      exposure:
        # we want all infos
        include: '*'
        # No env - passwords!
        exclude: env
    enabled-by-default: true
  endpoint:
    health:
      show-details: always

# ===================================================================
# Application specific properties
# ===================================================================

application:
  show-config-on-startup: true
  consumer:
    queue-name: 'QUEUE'

